#
###################################
# Site wide configuration
####################################
#
title: Harshal
email: harshalgupta826@gmail.com
description: 
url:


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Harshalbot
  avatar: 
  job: "Insights @ GreyOrange"
  bio: "Volunteer @headstarters • Previously @AxilorVentures | @EY_India • Everything Startups •"
  email: harshalgupta826@gmail.com
  disqus-shortname:
  twitter: harshalbot
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: harshalbot
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: harshalgupta
  skype: #username
  xing: #username
  instagram: harshal826
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
